name: we_chat
description: "silent-voice"
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For using cupertino icons
  cupertino_icons: ^1.0.8

  # For integrating firebase
  firebase_core: ^3.0.0

  # For handling firebase authentication
  firebase_auth: ^5.0.0

  # For handling google sign in
  google_sign_in: ^6.2.1

  # For accessing cloud firestore database
  cloud_firestore: ^5.0.0

  # For showing network images
  cached_network_image: ^3.3.1

  # For picking images
  image_picker: ^1.1.2

  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^12.0.0

  # For showing Emojis
  emoji_picker_flutter: ^2.2.0

  # For accessing firebase messaging (Push Notification)
  firebase_messaging: ^15.0.0

  # Bearer Token for Push Notification
  googleapis_auth: ^1.6.0

  # For calling RestAPIs
  http: ^1.2.1

  # For creating notification channel
  flutter_notification_channel: ^3.1.0

  # For storing images into gallery
  gallery_saver_updated: ^3.0.0

  # For Playing Lottie Animation
  lottie: ^3.1.2

  # Google Gemini Ai Integration
  google_generative_ai: ^0.4.3
  # For ML Model
  sliding_up_panel:
  path:
#  camera:
#  tflite:
  get: ^4.6.5
#  tflite_flutter: ^0.10.0



  shared_preferences: ^2.2.0
  flutter_svg: ^1.0.3
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  animated_bottom_navigation_bar: ^1.2.0
  photo_view: ^0.14.0


  dio: ^5.3.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  # sign language
#  camera: ^0.9.4+3
#  tflite: ^1.1.2
  native_screenshot: ^1.0.0
  flutter_tts: ^3.3.3
  image: ^3.1.3


  camera: ^0.10.5+7
#  tflite_v2: ^1.0.0

#  tflite_flutter:

  tflite_v2:
  percent_indicator:
  onnxruntime: ^1.4.1
  timer_builder:









dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

  # For recommended coding practices
  flutter_lints: ^4.0.0

flutter:
  # For enabling material design
  uses-material-design: true

  # App Assets
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/model/
    - assets/signs/
    - assets/model/git1/labels.txt
    - assets/model/git1/model_unquant.tflite
    - assets/model/labels.txt
    - assets/model/mobilenetv2_asl_model_final.tflite
    - assets/KIIT/tflite/model_unquant.tflite
    - assets/KIIT/tflite/labels.txt
    - assets/frontend/model.tflite
    - assets/frontend/labels.txt
    - assets/samiul/second_mobnet_model.tflite
    - assets/samiul/label.txt
