// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1agQF8nNs1DCz6l6KkY__tcD5v2CroFs',
    appId: '1:328288931432:android:e2a5ddb61584067b2135dd',
    messagingSenderId: '328288931432',
    projectId: 'test-chat-47cd4',
    storageBucket: 'test-chat-47cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJx7nBxokn13gv22s3VFF7VNUJ1X10T0',
    appId: '1:328288931432:ios:31006eee1379b2a02135dd',
    messagingSenderId: '328288931432',
    projectId: 'test-chat-47cd4',
    storageBucket: 'test-chat-47cd4.appspot.com',
    androidClientId: '328288931432-hqdqgpnaamgkrn01bfoj84rdpkor5vu0.apps.googleusercontent.com',
    iosClientId: '328288931432-gld16ec7580988nsrhikiluguno1csal.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-1MjB067GUwQHPnYmWkr_4iMz13UgRs',
    appId: '1:288842837392:web:6ae5bafc6d7d4f407a5715',
    messagingSenderId: '288842837392',
    projectId: 'we-chat-75f13',
    authDomain: 'we-chat-75f13.firebaseapp.com',
    storageBucket: 'we-chat-75f13.appspot.com',
  );

}